// import type { Metadata } from "next";
// import { Geist, Geist_Mono } from "next/font/google";
import { Inter } from "next/font/google";
import "./globals.css";

// const geistSans = Geist({
//   variable: "--font-geist-sans",
//   subsets: ["latin"],
// });

// const geistMono = Geist_Mono({
//   variable: "--font-geist-mono",
//   subsets: ["latin"],
// });

// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'My Next.js Website',
  description: 'Belajar Next.js untuk pemula',
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${inter.className} antialiased`}>
        {children}

        <footer className="bg-gray-800 text-white p-3 text-center bottom-0 left-0 w-full">
          <p>&copy; 2025 My Next JS Website build with ❤️☕</p>
        </footer>
      </body>
    </html>
  );
}
